[2024-07-12 06:54:38,186] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: task2_file_stg.load_chats manual__2024-07-12T06:54:35.989313+00:00 [queued]>
[2024-07-12 06:54:38,199] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: task2_file_stg.load_chats manual__2024-07-12T06:54:35.989313+00:00 [queued]>
[2024-07-12 06:54:38,200] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-07-12 06:54:38,200] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2024-07-12 06:54:38,200] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-07-12 06:54:38,214] {taskinstance.py:1259} INFO - Executing <Task(_PythonDecoratedOperator): load_chats> on 2024-07-12 06:54:35.989313+00:00
[2024-07-12 06:54:38,218] {standard_task_runner.py:52} INFO - Started process 6763 to run task
[2024-07-12 06:54:38,222] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'task2_file_stg', 'load_chats', 'manual__2024-07-12T06:54:35.989313+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/task2_file_stg.py', '--cfg-path', '/tmp/tmpua8xei1k', '--error-file', '/tmp/tmp0djhuga7']
[2024-07-12 06:54:38,226] {standard_task_runner.py:77} INFO - Job 17: Subtask load_chats
[2024-07-12 06:54:38,298] {logging_mixin.py:109} INFO - Running <TaskInstance: task2_file_stg.load_chats manual__2024-07-12T06:54:35.989313+00:00 [running]> on host 676d07ac814a
[2024-07-12 06:54:38,367] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=task2_file_stg
AIRFLOW_CTX_TASK_ID=load_chats
AIRFLOW_CTX_EXECUTION_DATE=2024-07-12T06:54:35.989313+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-07-12T06:54:35.989313+00:00
[2024-07-12 06:54:38,395] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/task2_file_stg.py", line 59, in load_chats
    load_csv_to_vertica("dags/files/chats.csv", "chats")
  File "/opt/airflow/dags/task2_file_stg.py", line 31, in load_csv_to_vertica
    cursor.execute(query, data)
  File "/home/airflow/.local/lib/python3.6/site-packages/vertica_python/vertica/cursor.py", line 237, in execute
    operation = self.format_operation_with_parameters(operation, parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/vertica_python/vertica/cursor.py", line 626, in format_operation_with_parameters
    operation = operation % tuple(tlist)
TypeError: not enough arguments for format string
[2024-07-12 06:54:38,414] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=task2_file_stg, task_id=load_chats, execution_date=20240712T065435, start_date=20240712T065438, end_date=20240712T065438
[2024-07-12 06:54:38,428] {standard_task_runner.py:92} ERROR - Failed to execute job 17 for task load_chats
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/decorators/base.py", line 134, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/task2_file_stg.py", line 59, in load_chats
    load_csv_to_vertica("dags/files/chats.csv", "chats")
  File "/opt/airflow/dags/task2_file_stg.py", line 31, in load_csv_to_vertica
    cursor.execute(query, data)
  File "/home/airflow/.local/lib/python3.6/site-packages/vertica_python/vertica/cursor.py", line 237, in execute
    operation = self.format_operation_with_parameters(operation, parameters)
  File "/home/airflow/.local/lib/python3.6/site-packages/vertica_python/vertica/cursor.py", line 626, in format_operation_with_parameters
    operation = operation % tuple(tlist)
TypeError: not enough arguments for format string
[2024-07-12 06:54:38,444] {local_task_job.py:154} INFO - Task exited with return code 1
[2024-07-12 06:54:38,502] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
